runtime: php55
api_version: 1

handlers:
- url: .*
  script: main.php

env_variables:
 DEVELOPMENT_DB_HOST: ''
 DEVELOPMENT_DB_USERNAME: 'root'
 DEVELOPMENT_DB_PASSWORD: 'mysql'
 DEVELOPMENT_DB_NAME: 'guestbook'
 PRODUCTION_CLOUD_SQL_INSTANCE: '/cloudsql/carbide-canto-153704:cloudsql'
 PRODUCTION_DB_USERNAME: 'riad'
 PRODUCTION_DB_PASSWORD: mysql''
 PRODUCTION_DB_NAME: 'guestbook'
